version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db/animals-local

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo

volumes:
  db-data:
    driver: local